#!/usr/bin/env python3

import os
import sys
import shutil

if len(sys.argv) < 2:
    print("Usage 'backup tag'")
    exit(1)

tag = sys.argv[1]

if os.path.exists("backups/" + tag):
    print("Tag already exists")
    exit(1)

shutil.copytree("build/classes", "backups/" + tag)
