#!/usr/bin/env python3

import os
import argparse
import shutil
import subprocess

parser = argparse.ArgumentParser(description='Run BattleCode Bots')
parser.add_argument("tag")
parser.add_argument("--nobuild", help="Don't build first", action="store_true")
args = parser.parse_args()

tag = args.tag

if os.path.exists("backups/" + tag):
    print("Tag already exists")
    exit(1)


def backup(tag):
    if not args.nobuild:
        print("Building...")
        try:
            subprocess.check_output(["./gradlew", "build"])
        except:
            return

    shutil.copytree("build/classes", "backups/" + tag)


backup(tag)
